remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Igor Dias da Silva
description: Ph.D. student in Computer Science at COATI, INRIA, France
show_downloads: false
